- hosts: webservers
  become: true
  vars_files: vars.yml

  tasks:
  - name: install bind9 and dns utils
    apt:
      name: ['dnsutils', 'bind9', ]
      state: present
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Configuration named.conf
    template:
      src: "templates/bind9.j2"
      dest: "/etc/bind/named.conf"
      owner: root
      group: root
      mode: 0644
    notify: Restart bind9


  handlers:
  - name: Restart bind9
    service:
      name: bind9
      state: restarted

